Understand basics of Data Frames in Pandas

In [2]:
import pandas as pd 
df = pd.DataFrame(
    {
        "101":["Sales","Mumbai"],
        "102":["SW","Pune"],
        "103":["Architects","Chennai"]
    })
df.describe()
df.columns
df.first
df.last
df.head(2)
df.tail(2)

      101   102         103
0   Sales    SW  Architects
1  Mumbai  Pune     Chennai

In [3]:
#Understand Structure of Data provided by source
empdf = pd.read_csv("employees.csv")
print(empdf.describe())
print("Shape : ", empdf.shape)
print("Columns : ", empdf.columns)
print("Types : ", empdf.dtypes)
print("Information : ",empdf.info())

              Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000
Shape :  (1000, 8)
Columns :  Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')
Types :  First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB
Information :  None

In [4]:
#Understand Structure of Data provided by source
empdf = pd.read_csv("employees.csv")
#empdf.head(5)
#empdf.tail(5)
#empdf.items

#slicing methods for rows
#empdf.iloc[4:12]
#result = empdf.loc[10:15, 'First Name']
#print(result)

#slicing for Columns with rows
resultcols = empdf.iloc[10:15,3:5] #Row range , column range
print(resultcols)

   Last Login Time  Salary
10         9:01 AM   63241
11         3:19 PM  102508
12         1:08 AM  112807
13        11:40 PM  109831
14         7:13 AM   41426

In [5]:
import pandas as pd

d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [6]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])

# Access the rows of the DataFrame
result = df.index
print('Output Accessed Row Labels:', result)
df.describe()

Output Accessed Row Labels: Index(['r1', 'r2', 'r3', 'r4'], dtype='object')

             Age    Rating
count   4.000000  4.000000
mean   35.750000  3.682500
std     7.410578  0.765436
min    28.000000  2.780000
25%    31.000000  3.282500
50%    35.000000  3.675000
75%    39.750000  4.075000
max    45.000000  4.600000

In [7]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])
    
# Display the Input DataFrame
print('Input DataFrame:\n', df)

# Modify the Column labels of the DataFrame
df.columns = ['Col1', 'Col2', 'Col3', 'Col4']
print('Output Modified DataFrame with the updated Column Labels\n:', df)

Input DataFrame:
      Name  Age  Gender  Rating
r1  Steve   32    Male    3.45
r2    Lia   28  Female    4.60
r3    Vin   45    Male    3.90
r4  Katie   38  Female    2.78
Output Modified DataFrame with the updated Column Labels
:      Col1  Col2    Col3  Col4
r1  Steve    32    Male  3.45
r2    Lia    28  Female  4.60
r3    Vin    45    Male  3.90
r4  Katie    38  Female  2.78

In [8]:
empdf = pd.read_csv("employees.csv")
col_A = empdf.loc[:, "First Name"]
print("Slicing a single column A using loc[]:")
print(col_A)

# Slice multiple columns by label
cols_AB = empdf.loc[:, "First Name":"Gender"]
print("Slicing Multiple columns A and B using loc[]:")
print(cols_AB)

sal = empdf.loc[:,"Salary"]
sum(sal)

bonus = empdf.loc[:,"Bonus %"]
sum(bonus)

Slicing a single column A using loc[]:
0      Douglas
1       Thomas
2        Maria
3        Jerry
4        Larry
        ...
995      Henry
996    Phillip
997    Russell
998      Larry
999     Albert
Name: First Name, Length: 1000, dtype: object
Slicing Multiple columns A and B using loc[]:
    First Name  Gender
0      Douglas    Male
1       Thomas    Male
2        Maria  Female
3        Jerry    Male
4        Larry    Male
..         ...     ...
995      Henry     NaN
996    Phillip    Male
997    Russell    Male
998      Larry    Male
999     Albert    Male

[1000 rows x 2 columns]

10207.554999999998

In [1]:
pip install lxml

Collecting lxml
  Using cached lxml-6.1.1-cp310-cp310-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp310-cp310-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   -------------------- ------------------- 2.1/4.0 MB 166.1 kB/s eta 0:00:12
   -------------------- ------------------- 2.1/4.0 MB 166.1 kB/s eta 0:00:12
   -------------------- ------------------- 2.1/4.0 MB 166.1 kB/s eta 0:00:12
   -------------------- ------------------- 2.1/4.0 MB 166.1 kB/s eta 0:00:12
   -------------------- ------------------- 2.1/4.0 MB 166.1 kB/s eta 0:00:12
   ----------------------- ---------------- 2.4/4.0 MB 172.5 kB/s eta 0:00:10
   ----------------------- ---------------- 2.4/4.0 MB 172.5 kB/s eta 0:00:10
   ----------------------- ---------------- 2.4/4.0 MB 172.5 kB/s eta 0:00:10
   ----------------------- ---------------- 2.4/4.0 MB 172.5 kB/s eta 0:00:10
   ----------------------- ---------------- 2.4/4.0 MB 172.5 kB/s eta 0:00:10
   -------------------------- ------------- 2.6/4.0 MB 179.5 kB/s eta 0:00:08
   -------------------------- ------------- 2.6/4.0 MB 179.5 kB/s eta 0:00:08
   -------------------------- ------------- 2.6/4.0 MB 179.5 kB/s eta 0:00:08
   -------------------------- ------------- 2.6/4.0 MB 179.5 kB/s eta 0:00:08
   -------------------------- ------------- 2.6/4.0 MB 179.5 kB/s eta 0:00:08
   ---------------------------- ----------- 2.9/4.0 MB 185.2 kB/s eta 0:00:07
   ---------------------------- ----------- 2.9/4.0 MB 185.2 kB/s eta 0:00:07
   ---------------------------- ----------- 2.9/4.0 MB 185.2 kB/s eta 0:00:07
   ---------------------------- ----------- 2.9/4.0 MB 185.2 kB/s eta 0:00:07
   ---------------------------- ----------- 2.9/4.0 MB 185.2 kB/s eta 0:00:07
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 118.0 kB/s  0:00:35
Installing collected packages: lxml
Successfully installed lxml-6.1.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

custdf = pd.read_json("myfile.json")
custdf.describe()

compdf = pd.read_xml("employees.xml", parser="etree")
compdf.describe()

userdf = pd.read_parquet("sample-users.parquet")
userdf.describe()

orcdf = pd.read_orc("orc_metadata_sample.orc")
orcdf.describe()

htmldf = pd.read_html("myfile.html")
htmldf[0].describe()

productsdf = pd.read_json("Products.json")
productsdf.describe()
df01 = productsdf["value"]
df01[1]

employeesdf = pd.read_excel("employees.xlsx")
employeesdf.describe()

              Salary      Bonus %  Senior Management
count    1000.000000  1000.000000         933.000000
mean    90662.181000    10.207555           0.501608
std     32923.693342     5.528481           0.500266
min     35013.000000     1.015000           0.000000
25%     62613.000000     5.401750           0.000000
50%     90428.000000     9.838500           1.000000
75%    118740.250000    14.838000           1.000000
max    149908.000000    19.944000           1.000000

In [12]:
employeesdf = pd.read_excel("employees.xlsx")
employeesdf.describe()

sorted_df = employeesdf.sort_values("Salary")#returns data frame object
sorted_df.head()

newsalseries = employeesdf["Salary"].sort_values()#Return series of sorted Salary values
newsalseries.head()

sumsal = employeesdf["Salary"].sum()
print(sumsal)

print("Count of rows with no Gender value:",employeesdf["Gender"].isna().sum())
employeesdf["Gender"].fillna('No Gender',inplace=True)
print("Count of rows with no Gender value:",employeesdf["Gender"].isna().sum())

90662181
Count of rows with no Gender value: 145
Count of rows with no Gender value: 0

C:\Users\Hait\AppData\Local\Temp\ipykernel_37688\4002897841.py:14: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  employeesdf["Gender"].fillna('No Gender',inplace=True)

In [23]:
import numpy as np
employeesdf = pd.read_excel("employees.xlsx")
print("Count of rows with no SM value:",employeesdf["Senior Management"].isna().sum())
employeesdf = employeesdf["Senior Management"].replace(to_replace=np.nan,value="TRUE")
print("Count of rows with no SM value:",employeesdf.isna().sum())

Count of rows with no SM value: 67
Count of rows with no SM value: 0

In [14]:
import pandas as pd
productsdf = pd.read_csv("products-1000.csv")
productsdf.describe()
productsdf.shape
print(productsdf.columns)

#productsdf.groupby("Color").count()
#productsdf.groupby("Category").count()
#productsdf.groupby("Availability").count()
productsdf.groupby("Size").count()

eankurtosis = productsdf["EAN"].kurtosis()
print("Kurtosis on EAN ",eankurtosis)

print(round(productsdf["Stock"].kurtosis(),3))
print(round(productsdf["Price"].skew(),3))
print("Mean ", round(productsdf["Price"].mean(),3))
print("Median ", round(productsdf["Price"].median(),3))
print("Mode ", round(productsdf["Price"].mode(),3))
print("Min ", min(productsdf["Price"]))
print("Max ", max(productsdf["Price"]))

#dfagg = productsdf.groupby("Availability").agg({"Price":"mean","Stock":"sum"})
#dfagg = productsdf.groupby("Color").agg({"Price":"mean","Stock":"sum"})
dfagg = productsdf.groupby("Category").aggregate({"Price":"median","Stock":"sum"})

Q1 = productsdf["Stock"].quantile(0.25)
Q3 = productsdf["Stock"].quantile(0.75)

IQR = Q3-Q1
lower = Q1 - 0.5 * IQR
upper = Q3 + 0.5 * IQR

outliers = productsdf["Stock"][(productsdf["Stock"] < lower) | (productsdf["Stock"] > upper)]
print("Outliers : ",outliers.count())

Index(['Index', 'Name', 'Description', 'Brand', 'Category', 'Price',
       'Currency', 'Stock', 'EAN', 'Color', 'Size', 'Availability',
       'Internal ID'],
      dtype='object')
Kurtosis on EAN  -1.1974659340471765
-1.215
0.036
Mean  506.549
Median  497.5
Mode  0    256
Name: Price, dtype: int64
Min  1
Max  999
Outliers :  0

In [ ]:
#Data Frame Manipulation
import pandas as pd

# create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'London', 'Paris', 'Tokyo'],
        'Height': ['165', '178', '185', '171'],
        'Profession': ['Engineer', 'Entrepreneur', 'Unemployed', 'Actor'],
        'Marital Status': ['Single', 'Married', 'Divorced', 'Engaged']}

df = pd.DataFrame(data)

# convert the dictionary into a DataFrame
df = pd.DataFrame(data)
df

#Adding a new column as Address
# declare a new list
address = ['New York', 'London', 'Sydney', 'Toronto']

# assign the list as a column
df['Address'] = address

print(df)

#Adding new Row to a Data Frame
df.loc[len(df.index)] = ["Ganesh", "5.6", "Msc.","Pune"]
print(df)

      Name  Height Qualification   Address
0     John     5.5           BSc  New York
1     Emma     6.0           BBA    London
2  Michael     5.8           MBA    Sydney
3   Sophia     5.3           BSc   Toronto
      Name Height Qualification   Address
0     John    5.5           BSc  New York
1     Emma    6.0           BBA    London
2  Michael    5.8           MBA    Sydney
3   Sophia    5.3           BSc   Toronto
4   Ganesh    5.6          Msc.      Pune

In [51]:
import pandas as pd

# create a sample DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 30, 35, 40],
        'City': ['New York', 'London', 'Paris', 'Tokyo'],
        'Height': ['165', '178', '185', '171'],
        'Profession': ['Engineer', 'Entrepreneur', 'Unemployed', 'Actor'],
        'Marital Status': ['Single', 'Married', 'Divorced', 'Engaged']}
df = pd.DataFrame(data)

# display the original DataFrame
print("Original DataFrame:")
print(df)
print()

#drop / delete row
df.drop(index=3)

# delete age column
df.drop('Age', axis=1, inplace=True)

# delete marital status column
df.drop(columns='Marital Status', inplace=True)

# delete height and profession columns
df.drop(['Height', 'Profession'], axis=1, inplace=True)

# display the modified DataFrame after deleting rows
print("Modified DataFrame:")
print(df)

Original DataFrame:
      Name  Age      City Height    Profession Marital Status
0    Alice   25  New York    165      Engineer         Single
1      Bob   30    London    178  Entrepreneur        Married
2  Charlie   35     Paris    185    Unemployed       Divorced
3    David   40     Tokyo    171         Actor        Engaged

Modified DataFrame:
      Name      City
0    Alice  New York
1      Bob    London
2  Charlie     Paris
3    David     Tokyo

In [56]:
import numpy as np
#Drop rows with null values
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
df = pd.DataFrame(dict)
df.dropna(inplace=True)
df

   First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [57]:
import pandas as pd
  
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
 
df = pd.DataFrame(dict)

for i, j in df.iterrows():
    print(i, j)
    print()

0 name      aparna
degree       MBA
score         90
Name: 0, dtype: object

1 name      pankaj
degree       BCA
score         40
Name: 1, dtype: object

2 name      sudhir
degree    M.Tech
score         80
Name: 2, dtype: object

3 name      Geeku
degree      MBA
score        98
Name: 3, dtype: object

In [6]:
import pandas as pd

# create a DataFrame
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Department': ['HR', 'Marketing', 'Marketing', 'IT'],
        'Salary': [50000, 60000, 55000, 70000]}

df = pd.DataFrame(data)

# display the original DataFrame
print("Original DataFrame:")
print(df)
print("\n")

# use the filter() method to select columns based on a condition
filtered_df = df.filter(items=['Name', 'Salary']) 

# display the filtered DataFrame
#print("Filtered DataFrame:")
#print(filtered_df)

filtered_df = df[df.Salary>50000]
#print(filtered_df)

depts = ["HR","IT"]
filtered_df = df[df.Department.isin(depts)]
#print(filtered_df)

filtered_df = df[df.Department.str.contains('Market')]
#print(filtered_df)

filtered_df = df.query('Salary > 55000 and Department == "Marketing"')
print(filtered_df)

Original DataFrame:
      Name Department  Salary
0    Alice         HR   50000
1      Bob  Marketing   60000
2  Charlie  Marketing   55000
3    David         IT   70000


  Name Department  Salary
1  Bob  Marketing   60000

In [8]:
import pandas as pd

data = {'Name': ['Alice', 'Bob', 'Charlie', 'David'],
        'Age': [25, 22, 30, 22],
        'Score': [85, 90, 75, 80]}
df.info()
df = pd.DataFrame(data)

# 1. Sort DataFrame by 'Age' and then by 'Score' (Both in ascending order)
df1 = df.sort_values(by=['Age', 'Score'])

print("Sorting by 'Age' (ascending) and then by 'Score' (ascending):\n")
print(df1.to_string(index=False))

print()
# 2. Sort DataFrame by 'Age' in ascending order, and then by 'Score' in descending order
df2 = df.sort_values(by=['Age', 'Score'], ascending=[True, False])

print("Sorting by 'Age' (ascending) and then by 'Score' (descending):\n")
print(df2.to_string(index=False))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    4 non-null      object
 1   Age     4 non-null      int64
 2   Score   4 non-null      int64
dtypes: int64(2), object(1)
memory usage: 224.0+ bytes
Sorting by 'Age' (ascending) and then by 'Score' (ascending):

   Name  Age  Score
  David   22     80
    Bob   22     90
  Alice   25     85
Charlie   30     75

Sorting by 'Age' (ascending) and then by 'Score' (descending):

   Name  Age  Score
    Bob   22     90
  David   22     80
  Alice   25     85
Charlie   30     75

In [18]:
import numpy as np
A = np.array([[50, 29], [30, 44]])
sign, logdet = np.linalg.slogdet(A)
res = sign * np.exp(logdet)
print(res)


A2 = np.array([[10, 20, 3], [4 ,5, 6], [7, 8, 9]])
res = np.linalg.det(A2)
print(res)

1330.0000000000002
81.0000000000001