Understand basics of Data Frames in Pandas

In [2]:
import pandas as pd 
df = pd.DataFrame(
    {
        "101":["Sales","Mumbai"],
        "102":["SW","Pune"],
        "103":["Architects","Chennai"]
    })
df.describe()
df.columns
df.first
df.last
df.head(2)
df.tail(2)

      101   102         103
0   Sales    SW  Architects
1  Mumbai  Pune     Chennai

In [3]:
#Understand Structure of Data provided by source
empdf = pd.read_csv("employees.csv")
print(empdf.describe())
print("Shape : ", empdf.shape)
print("Columns : ", empdf.columns)
print("Types : ", empdf.dtypes)
print("Information : ",empdf.info())

              Salary      Bonus %
count    1000.000000  1000.000000
mean    90662.181000    10.207555
std     32923.693342     5.528481
min     35013.000000     1.015000
25%     62613.000000     5.401750
50%     90428.000000     9.838500
75%    118740.250000    14.838000
max    149908.000000    19.944000
Shape :  (1000, 8)
Columns :  Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')
Types :  First Name            object
Gender                object
Start Date            object
Last Login Time       object
Salary                 int64
Bonus %              float64
Senior Management     object
Team                  object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   First Name         933 non-null    object
 1   Gender             855 non-null    object
 2   Start Date         1000 non-null   object
 3   Last Login Time    1000 non-null   object
 4   Salary             1000 non-null   int64
 5   Bonus %            1000 non-null   float64
 6   Senior Management  933 non-null    object
 7   Team               957 non-null    object
dtypes: float64(1), int64(1), object(6)
memory usage: 62.6+ KB
Information :  None

In [4]:
#Understand Structure of Data provided by source
empdf = pd.read_csv("employees.csv")
#empdf.head(5)
#empdf.tail(5)
#empdf.items

#slicing methods for rows
#empdf.iloc[4:12]
#result = empdf.loc[10:15, 'First Name']
#print(result)

#slicing for Columns with rows
resultcols = empdf.iloc[10:15,3:5] #Row range , column range
print(resultcols)

   Last Login Time  Salary
10         9:01 AM   63241
11         3:19 PM  102508
12         1:08 AM  112807
13        11:40 PM  109831
14         7:13 AM   41426

In [5]:
import pandas as pd

d = {'one' : pd.Series([1, 2, 3], index=['a', 'b', 'c']),
   'two' : pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])}

df = pd.DataFrame(d)
print(df)

   one  two
a  1.0    1
b  2.0    2
c  3.0    3
d  NaN    4

In [6]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])

# Access the rows of the DataFrame
result = df.index
print('Output Accessed Row Labels:', result)
df.describe()

Output Accessed Row Labels: Index(['r1', 'r2', 'r3', 'r4'], dtype='object')

             Age    Rating
count   4.000000  4.000000
mean   35.750000  3.682500
std     7.410578  0.765436
min    28.000000  2.780000
25%    31.000000  3.282500
50%    35.000000  3.675000
75%    39.750000  4.075000
max    45.000000  4.600000

In [7]:
import pandas as pd

# Create a DataFrame
df = pd.DataFrame({
    'Name': ['Steve', 'Lia', 'Vin', 'Katie'],
    'Age': [32, 28, 45, 38],
    'Gender': ['Male', 'Female', 'Male', 'Female'],
    'Rating': [3.45, 4.6, 3.9, 2.78]},
    index=['r1', 'r2', 'r3', 'r4'])
    
# Display the Input DataFrame
print('Input DataFrame:\n', df)

# Modify the Column labels of the DataFrame
df.columns = ['Col1', 'Col2', 'Col3', 'Col4']
print('Output Modified DataFrame with the updated Column Labels\n:', df)

Input DataFrame:
      Name  Age  Gender  Rating
r1  Steve   32    Male    3.45
r2    Lia   28  Female    4.60
r3    Vin   45    Male    3.90
r4  Katie   38  Female    2.78
Output Modified DataFrame with the updated Column Labels
:      Col1  Col2    Col3  Col4
r1  Steve    32    Male  3.45
r2    Lia    28  Female  4.60
r3    Vin    45    Male  3.90
r4  Katie    38  Female  2.78

In [8]:
empdf = pd.read_csv("employees.csv")
col_A = empdf.loc[:, "First Name"]
print("Slicing a single column A using loc[]:")
print(col_A)

# Slice multiple columns by label
cols_AB = empdf.loc[:, "First Name":"Gender"]
print("Slicing Multiple columns A and B using loc[]:")
print(cols_AB)

sal = empdf.loc[:,"Salary"]
sum(sal)

bonus = empdf.loc[:,"Bonus %"]
sum(bonus)

Slicing a single column A using loc[]:
0      Douglas
1       Thomas
2        Maria
3        Jerry
4        Larry
        ...
995      Henry
996    Phillip
997    Russell
998      Larry
999     Albert
Name: First Name, Length: 1000, dtype: object
Slicing Multiple columns A and B using loc[]:
    First Name  Gender
0      Douglas    Male
1       Thomas    Male
2        Maria  Female
3        Jerry    Male
4        Larry    Male
..         ...     ...
995      Henry     NaN
996    Phillip    Male
997    Russell    Male
998      Larry    Male
999     Albert    Male

[1000 rows x 2 columns]

10207.554999999998

In [1]:
pip install lxml

Collecting lxml
  Using cached lxml-6.1.1-cp310-cp310-win_amd64.whl.metadata (3.6 kB)
Downloading lxml-6.1.1-cp310-cp310-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ----- ---------------------------------- 0.5/4.0 MB 159.7 kB/s eta 0:00:22
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ------- -------------------------------- 0.8/4.0 MB 171.2 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ---------- ----------------------------- 1.0/4.0 MB 158.3 kB/s eta 0:00:19
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   ------------- -------------------------- 1.3/4.0 MB 166.5 kB/s eta 0:00:17
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   --------------- ------------------------ 1.6/4.0 MB 174.8 kB/s eta 0:00:15
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   ------------------ --------------------- 1.8/4.0 MB 166.1 kB/s eta 0:00:14
   -------------------- ------------------- 2.1/4.0 MB 166.1 kB/s eta 0:00:12
   -------------------- ------------------- 2.1/4.0 MB 166.1 kB/s eta 0:00:12
   -------------------- ------------------- 2.1/4.0 MB 166.1 kB/s eta 0:00:12
   -------------------- ------------------- 2.1/4.0 MB 166.1 kB/s eta 0:00:12
   -------------------- ------------------- 2.1/4.0 MB 166.1 kB/s eta 0:00:12
   ----------------------- ---------------- 2.4/4.0 MB 172.5 kB/s eta 0:00:10
   ----------------------- ---------------- 2.4/4.0 MB 172.5 kB/s eta 0:00:10
   ----------------------- ---------------- 2.4/4.0 MB 172.5 kB/s eta 0:00:10
   ----------------------- ---------------- 2.4/4.0 MB 172.5 kB/s eta 0:00:10
   ----------------------- ---------------- 2.4/4.0 MB 172.5 kB/s eta 0:00:10
   -------------------------- ------------- 2.6/4.0 MB 179.5 kB/s eta 0:00:08
   -------------------------- ------------- 2.6/4.0 MB 179.5 kB/s eta 0:00:08
   -------------------------- ------------- 2.6/4.0 MB 179.5 kB/s eta 0:00:08
   -------------------------- ------------- 2.6/4.0 MB 179.5 kB/s eta 0:00:08
   -------------------------- ------------- 2.6/4.0 MB 179.5 kB/s eta 0:00:08
   ---------------------------- ----------- 2.9/4.0 MB 185.2 kB/s eta 0:00:07
   ---------------------------- ----------- 2.9/4.0 MB 185.2 kB/s eta 0:00:07
   ---------------------------- ----------- 2.9/4.0 MB 185.2 kB/s eta 0:00:07
   ---------------------------- ----------- 2.9/4.0 MB 185.2 kB/s eta 0:00:07
   ---------------------------- ----------- 2.9/4.0 MB 185.2 kB/s eta 0:00:07
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   ------------------------------- -------- 3.1/4.0 MB 188.3 kB/s eta 0:00:05
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   --------------------------------- ------ 3.4/4.0 MB 173.0 kB/s eta 0:00:04
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ------------------------------------ --- 3.7/4.0 MB 133.9 kB/s eta 0:00:03
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------  3.9/4.0 MB 126.0 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 118.0 kB/s  0:00:35
Installing collected packages: lxml
Successfully installed lxml-6.1.1
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [1]:
import pandas as pd

custdf = pd.read_json("myfile.json")
custdf.describe()

compdf = pd.read_xml("employees.xml", parser="etree")
compdf.describe()

userdf = pd.read_parquet("sample-users.parquet")
userdf.describe()

orcdf = pd.read_orc("orc_metadata_sample.orc")
orcdf.describe()

htmldf = pd.read_html("myfile.html")
htmldf[0].describe()

productsdf = pd.read_json("Products.json")
productsdf.describe()
df01 = productsdf["value"]
df01[1]

employeesdf = pd.read_excel("employees.xlsx")
employeesdf.describe()

              Salary      Bonus %  Senior Management
count    1000.000000  1000.000000         933.000000
mean    90662.181000    10.207555           0.501608
std     32923.693342     5.528481           0.500266
min     35013.000000     1.015000           0.000000
25%     62613.000000     5.401750           0.000000
50%     90428.000000     9.838500           1.000000
75%    118740.250000    14.838000           1.000000
max    149908.000000    19.944000           1.000000